insert into public.food_items (
  name,
  normalized_name,
  serving_size_g,
  calories_per_100g,
  protein_g_per_100g,
  carbs_g_per_100g,
  fat_g_per_100g,
  food_kind,
  category_slug,
  image_key,
  source,
  source_reference,
  is_verified
)
values
  ('Phở bò', 'pho bo', 100, 158, 9.1, 19.2, 5.0, 'dish', 'noodles', 'pho-bo-v1', 'Dữ liệu món Việt Nam tham khảo', null, true),
  ('Phở gà', 'pho ga', 100, 142, 10.1, 18.4, 3.2, 'dish', 'noodles', 'pho-ga-v1', 'Dữ liệu món Việt Nam tham khảo', null, true),
  ('Bún bò Huế', 'bun bo hue', 100, 165, 8.8, 20.1, 5.4, 'dish', 'noodles', 'bun-bo-hue-v1', 'Dữ liệu món Việt Nam tham khảo', null, true),
  ('Bún chả', 'bun cha', 100, 177, 8.7, 22.4, 5.8, 'dish', 'noodles', 'bun-cha-v1', 'Dữ liệu món Việt Nam tham khảo', null, true),
  ('Hủ tiếu', 'hu tieu', 100, 145, 7.2, 21.3, 3.4, 'dish', 'noodles', 'hu-tieu-v1', 'Dữ liệu món Việt Nam tham khảo', null, true),
  ('Mì Quảng', 'mi quang', 100, 164, 8.9, 21.0, 5.1, 'dish', 'noodles', 'mi-quang-v1', 'Dữ liệu món Việt Nam tham khảo', null, true),
  ('Cơm tấm sườn', 'com tam suon', 100, 230, 11.5, 28.4, 7.9, 'dish', 'rice-dishes', 'com-tam-suon-v1', 'Dữ liệu món Việt Nam tham khảo', null, true),
  ('Cơm gà nướng', 'com ga nuong', 100, 186, 12.4, 20.8, 6.1, 'dish', 'rice-dishes', 'com-ga-nuong-v1', 'Dữ liệu món Việt Nam tham khảo', null, true),
  ('Cơm chiên Dương Châu', 'com chien duong chau', 100, 190, 6.2, 27.1, 6.3, 'dish', 'rice-dishes', 'com-chien-duong-chau-v1', 'Dữ liệu món Việt Nam tham khảo', null, true),
  ('Bánh mì thịt', 'banh mi thit', 100, 274, 12.0, 36.0, 9.2, 'dish', 'bread', 'banh-mi-thit-v1', 'Dữ liệu món Việt Nam tham khảo', null, true),
  ('Bánh mì trứng', 'banh mi trung', 100, 265, 10.2, 32.0, 10.5, 'dish', 'bread', 'banh-mi-trung-v1', 'Dữ liệu món Việt Nam tham khảo', null, true),
  ('Bánh cuốn', 'banh cuon', 100, 181, 6.1, 27.5, 5.1, 'dish', 'bread', 'banh-cuon-v1', 'Dữ liệu món Việt Nam tham khảo', null, true),
  ('Gỏi cuốn', 'goi cuon', 100, 152, 8.4, 22.0, 3.4, 'dish', 'bread', 'goi-cuon-v1', 'Dữ liệu món Việt Nam tham khảo', null, true),
  ('Cháo gà', 'chao ga', 100, 93, 6.8, 12.5, 1.8, 'dish', 'soups', 'chao-ga-v1', 'Dữ liệu món Việt Nam tham khảo', null, true),
  ('Cá kho tộ', 'ca kho to', 100, 176, 21.4, 5.8, 7.2, 'dish', 'protein', 'ca-kho-to-v1', 'Dữ liệu món Việt Nam tham khảo', null, true),
  ('Canh chua cá', 'canh chua ca', 100, 74, 7.9, 6.2, 2.1, 'dish', 'soups', 'canh-chua-ca-v1', 'Dữ liệu món Việt Nam tham khảo', null, true),
  ('Ức gà áp chảo', 'uc ga ap chao', 100, 165, 31.0, 0, 3.6, 'ingredient', 'protein', 'uc-ga-ap-chao-v1', 'USDA FoodData Central', 'https://fdc.nal.usda.gov/', true),
  ('Đùi gà bỏ da', 'dui ga bo da', 100, 179, 24.8, 0, 8.2, 'ingredient', 'protein', 'dui-ga-bo-da-v1', 'USDA FoodData Central', 'https://fdc.nal.usda.gov/', true),
  ('Thịt bò nạc', 'thit bo nac', 100, 187, 26.1, 0, 8.2, 'ingredient', 'protein', 'thit-bo-nac-v1', 'USDA FoodData Central', 'https://fdc.nal.usda.gov/', true),
  ('Thịt heo nạc', 'thit heo nac', 100, 195, 29.0, 0, 8.0, 'ingredient', 'protein', 'thit-heo-nac-v1', 'USDA FoodData Central', 'https://fdc.nal.usda.gov/', true),
  ('Cá hồi', 'ca hoi', 100, 208, 20.4, 0, 13.4, 'ingredient', 'protein', 'ca-hoi-v1', 'USDA FoodData Central', 'https://fdc.nal.usda.gov/', true),
  ('Cá ngừ', 'ca ngu', 100, 132, 28.2, 0, 1.3, 'ingredient', 'protein', 'ca-ngu-v1', 'USDA FoodData Central', 'https://fdc.nal.usda.gov/', true),
  ('Cá rô phi', 'ca ro phi', 100, 128, 26.2, 0, 2.7, 'ingredient', 'protein', 'ca-ro-phi-v1', 'USDA FoodData Central', 'https://fdc.nal.usda.gov/', true),
  ('Tôm', 'tom', 100, 99, 24.0, 0.2, 0.3, 'ingredient', 'protein', 'tom-v1', 'USDA FoodData Central', 'https://fdc.nal.usda.gov/', true),
  ('Trứng gà luộc', 'trung ga luoc', 100, 155, 12.6, 1.1, 10.6, 'ingredient', 'protein', 'trung-ga-luoc-v1', 'USDA FoodData Central', 'https://fdc.nal.usda.gov/', true),
  ('Đậu hũ', 'dau hu', 100, 76, 8.1, 1.9, 4.8, 'ingredient', 'protein', 'dau-hu-v1', 'USDA FoodData Central', 'https://fdc.nal.usda.gov/', true),
  ('Cơm trắng', 'com trang', 100, 130, 2.7, 28.2, 0.3, 'ingredient', 'staples', 'com-trang-v1', 'USDA FoodData Central', 'https://fdc.nal.usda.gov/', true),
  ('Cơm gạo lứt', 'com gao lut', 100, 123, 2.7, 25.6, 1.0, 'ingredient', 'staples', 'com-gao-lut-v1', 'USDA FoodData Central', 'https://fdc.nal.usda.gov/', true),
  ('Khoai lang', 'khoai lang', 100, 86, 1.6, 20.1, 0.1, 'ingredient', 'staples', 'khoai-lang-v1', 'USDA FoodData Central', 'https://fdc.nal.usda.gov/', true),
  ('Khoai tây', 'khoai tay', 100, 77, 2.1, 17.5, 0.1, 'ingredient', 'staples', 'khoai-tay-v1', 'USDA FoodData Central', 'https://fdc.nal.usda.gov/', true),
  ('Yến mạch', 'yen mach', 100, 389, 16.9, 66.3, 6.9, 'ingredient', 'staples', 'yen-mach-v1', 'USDA FoodData Central', 'https://fdc.nal.usda.gov/', true),
  ('Bún tươi', 'bun tuoi', 100, 109, 1.8, 25.0, 0.2, 'ingredient', 'staples', 'bun-tuoi-v1', 'Bảng thành phần thực phẩm Việt Nam', null, true),
  ('Bông cải xanh', 'bong cai xanh', 100, 34, 2.8, 6.6, 0.4, 'ingredient', 'vegetables', 'bong-cai-xanh-v1', 'USDA FoodData Central', 'https://fdc.nal.usda.gov/', true),
  ('Rau muống', 'rau muong', 100, 19, 2.6, 3.1, 0.2, 'ingredient', 'vegetables', 'rau-muong-v1', 'USDA FoodData Central', 'https://fdc.nal.usda.gov/', true),
  ('Rau chân vịt', 'rau chan vit', 100, 23, 2.9, 3.6, 0.4, 'ingredient', 'vegetables', 'rau-chan-vit-v1', 'USDA FoodData Central', 'https://fdc.nal.usda.gov/', true),
  ('Cà rốt', 'ca rot', 100, 41, 0.9, 9.6, 0.2, 'ingredient', 'vegetables', 'ca-rot-v1', 'USDA FoodData Central', 'https://fdc.nal.usda.gov/', true),
  ('Cà chua', 'ca chua', 100, 18, 0.9, 3.9, 0.2, 'ingredient', 'vegetables', 'ca-chua-v1', 'USDA FoodData Central', 'https://fdc.nal.usda.gov/', true),
  ('Dưa leo', 'dua leo', 100, 15, 0.7, 3.6, 0.1, 'ingredient', 'vegetables', 'dua-leo-v1', 'USDA FoodData Central', 'https://fdc.nal.usda.gov/', true),
  ('Nấm mỡ', 'nam mo', 100, 22, 3.1, 3.3, 0.3, 'ingredient', 'vegetables', 'nam-mo-v1', 'USDA FoodData Central', 'https://fdc.nal.usda.gov/', true),
  ('Chuối', 'chuoi', 100, 89, 1.1, 22.8, 0.3, 'ingredient', 'fruit', 'chuoi-v1', 'USDA FoodData Central', 'https://fdc.nal.usda.gov/', true),
  ('Táo', 'tao', 100, 52, 0.3, 13.8, 0.2, 'ingredient', 'fruit', 'tao-v1', 'USDA FoodData Central', 'https://fdc.nal.usda.gov/', true),
  ('Cam', 'cam', 100, 47, 0.9, 11.8, 0.1, 'ingredient', 'fruit', 'cam-v1', 'USDA FoodData Central', 'https://fdc.nal.usda.gov/', true),
  ('Thanh long', 'thanh long', 100, 60, 1.2, 13.0, 0.4, 'ingredient', 'fruit', 'thanh-long-v1', 'Bảng thành phần thực phẩm Việt Nam', null, true),
  ('Bơ', 'bo', 100, 160, 2.0, 8.5, 14.7, 'ingredient', 'fruit', 'bo-v1', 'USDA FoodData Central', 'https://fdc.nal.usda.gov/', true),
  ('Xoài', 'xoai', 100, 60, 0.8, 15.0, 0.4, 'ingredient', 'fruit', 'xoai-v1', 'USDA FoodData Central', 'https://fdc.nal.usda.gov/', true),
  ('Sữa tươi không đường', 'sua tuoi khong duong', 100, 61, 3.2, 4.8, 3.3, 'drink', 'dairy', 'sua-tuoi-khong-duong-v1', 'USDA FoodData Central', 'https://fdc.nal.usda.gov/', true),
  ('Sữa chua không đường', 'sua chua khong duong', 100, 63, 5.3, 7.0, 1.6, 'ingredient', 'dairy', 'sua-chua-khong-duong-v1', 'USDA FoodData Central', 'https://fdc.nal.usda.gov/', true),
  ('Sữa đậu nành không đường', 'sua dau nanh khong duong', 100, 33, 2.9, 1.7, 1.6, 'drink', 'drinks', 'sua-dau-nanh-khong-duong-v1', 'USDA FoodData Central', 'https://fdc.nal.usda.gov/', true),
  ('Nước mắm', 'nuoc mam', 100, 35, 5.1, 3.6, 0, 'seasoning', 'seasonings', 'nuoc-mam-v1', 'USDA FoodData Central', 'https://fdc.nal.usda.gov/', true),
  ('Nước tương', 'nuoc tuong', 100, 53, 8.1, 4.9, 0.6, 'seasoning', 'seasonings', 'nuoc-tuong-v1', 'USDA FoodData Central', 'https://fdc.nal.usda.gov/', true),
  ('Dầu hào', 'dau hao', 100, 51, 1.4, 10.9, 0.3, 'seasoning', 'seasonings', 'dau-hao-v1', 'USDA FoodData Central', 'https://fdc.nal.usda.gov/', true),
  ('Đường trắng', 'duong trang', 100, 387, 0, 100, 0, 'seasoning', 'seasonings', 'duong-trang-v1', 'USDA FoodData Central', 'https://fdc.nal.usda.gov/', true),
  ('Dầu ô liu', 'dau o liu', 100, 884, 0, 0, 100, 'seasoning', 'seasonings', 'dau-o-liu-v1', 'USDA FoodData Central', 'https://fdc.nal.usda.gov/', true),
  ('Muối', 'muoi', 100, 0, 0, 0, 0, 'seasoning', 'seasonings', 'muoi-v1', 'USDA FoodData Central', 'https://fdc.nal.usda.gov/', true)
on conflict (normalized_name) where is_verified
  do update set
    name = excluded.name,
    serving_size_g = excluded.serving_size_g,
    calories_per_100g = excluded.calories_per_100g,
    protein_g_per_100g = excluded.protein_g_per_100g,
    carbs_g_per_100g = excluded.carbs_g_per_100g,
    fat_g_per_100g = excluded.fat_g_per_100g,
    food_kind = excluded.food_kind,
    category_slug = excluded.category_slug,
    image_key = excluded.image_key,
    source = excluded.source,
    source_reference = excluded.source_reference,
    updated_at = now();
